MEDIAPIPE_POINTS = [
    "NOSE", "LEFT_EYE_INNER", "LEFT_EYE", "LEFT_EYE_OUTER", 
    "RIGHT_EYE_INNER", "RIGHT_EYE", "RIGHT_EYE_OUTER", 
    "LEFT_EAR", "RIGHT_EAR", "MOUTH_LEFT", "MOUTH_RIGHT",
    "LEFT_SHOULDER", "RIGHT_SHOULDER", "LEFT_ELBOW", "RIGHT_ELBOW", 
    "LEFT_WRIST", "RIGHT_WRIST", "LEFT_PINKY", "RIGHT_PINKY", 
    "LEFT_INDEX", "RIGHT_INDEX", "LEFT_THUMB", "RIGHT_THUMB",
    "LEFT_HIP", "RIGHT_HIP", "LEFT_KNEE", "RIGHT_KNEE", 
    "LEFT_ANKLE", "RIGHT_ANKLE", "LEFT_HEEL", "RIGHT_HEEL", 
    "LEFT_FOOT_INDEX", "RIGHT_FOOT_INDEX"
]

DOF1_angles = {
    "LEFT_ELBOW": ('LEFT_SHOULDER', 'LEFT_ELBOW', 'LEFT_WRIST'),
    "RIGHT_ELBOW": ('RIGHT_SHOULDER', 'RIGHT_ELBOW', 'RIGHT_WRIST'),
    "LEFT_KNEE": ('LEFT_HIP', 'LEFT_KNEE', 'LEFT_ANKLE'),
    "RIGHT_KNEE": ('RIGHT_HIP', 'RIGHT_KNEE', 'RIGHT_ANKLE'),
    "LEFT_WRIST": ('LEFT_ELBOW', 'LEFT_WRIST', 'LEFT_INDEX'),
    "RIGHT_WRIST": ('RIGHT_ELBOW', 'RIGHT_WRIST', 'RIGHT_INDEX'),
    "LEFT_ANKLE": ('LEFT_KNEE', 'LEFT_ANKLE', 'LEFT_FOOT_INDEX'),
    "RIGHT_ANKLE": ('RIGHT_KNEE', 'RIGHT_ANKLE', 'RIGHT_FOOT_INDEX')
}

DOF3_angles = {
    "LEFT_SHOULDER_PITCH": ('LEFT_SHOULDER', 'LEFT_ELBOW', 'sagittal'),
    "LEFT_SHOULDER_ROLL": ('LEFT_SHOULDER', 'LEFT_ELBOW', 'coronal'),
    "RIGHT_SHOULDER_PITCH": ('RIGHT_SHOULDER', 'RIGHT_ELBOW', 'sagittal'),
    "RIGHT_SHOULDER_ROLL": ('RIGHT_SHOULDER', 'RIGHT_ELBOW', 'coronal'),

    "LEFT_HIP_PITCH": ('LEFT_HIP', 'LEFT_KNEE', 'sagittal'),
    "LEFT_HIP_ROLL": ('LEFT_HIP', 'LEFT_KNEE', 'coronal'),
    "RIGHT_HIP_PITCH": ('RIGHT_HIP', 'RIGHT_KNEE', 'sagittal'),
    "RIGHT_HIP_ROLL": ('RIGHT_HIP', 'RIGHT_KNEE', 'coronal'),

    "LEFT_FOOT_PITCH": ('LEFT_HEEL', 'LEFT_FOOT_INDEX', 'sagittal'),
    "RIGHT_FOOT_PITCH": ('RIGHT_HEEL', 'RIGHT_FOOT_INDEX', 'sagittal'),

    "SPINE_PITCH": ('PELVIS', 'NECK_BASE', 'sagittal'),
    "SPINE_ROLL": ('PELVIS', 'NECK_BASE', 'coronal'),
    "SPINE_YAW": ('PELVIS', 'NECK_BASE', 'transverse'),

    "NECK_PITCH": ('NECK_BASE', 'NOSE', 'sagittal'),
    "NECK_ROLL": ('NECK_BASE', 'NOSE', 'coronal'),
    "NECK_YAW": ('NECK_BASE', 'NOSE', 'transverse')
}

BONES = {
    'NECK_BONE' : ('NECK_BASE', 'NOSE'),
    'SPINE' : ('NECK_BASE', 'PELVIS'),
    'COLLAR_BONE' : ('LEFT_SHOULDER', 'RIGHT_SHOULDER'),
    'LEFT_HUMERUS' : ('LEFT_SHOULDER', 'LEFT_ELBOW'),
    'RIGHT_HUMERUS' : ('RIGHT_SHOULDER', 'RIGHT_ELBOW'),
    'LEFT_ULNA' : ('LEFT_ELBOW', 'LEFT_WRIST'),
    'RIGHT_ULNA' : ('RIGHT_ELBOW', 'RIGHT_WRIST'),
    'RIGHT_FEMUR' : ('RIGHT_HIP', 'RIGHT_KNEE'),
    'LEFT_FEMUR' : ('LEFT_HIP', 'LEFT_KNEE'),
    'LEFT_TIBIA' : ('LEFT_KNEE', 'LEFT_ANKLE'),
    'RIGHT_TIBIA' : ('RIGHT_KNEE', 'RIGHT_ANKLE')
}